# NOTE: This file is auto generated by OpenAPI Generator 7.12.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Ory.Model.IdentityWithCredentialsOidcConfigProvider do
  @moduledoc """
  Create Identity and Import Social Sign In Credentials Configuration
  """

  @derive Jason.Encoder
  defstruct [
    :provider,
    :subject
  ]

  @type t :: %__MODULE__{
    :provider => String.t,
    :subject => String.t
  }

  def decode(value) do
    value
  end
end

